//
//  Schedule.swift
//  CampusAppChallenge
//
//  Created by Rafał Małczyński on 13.01.2018.
//  Copyright © 2018 Lukasz Kawka. All rights reserved.
//

import Foundation

struct Schedule {
    var events: [Event] = [
        Event(name: "Logic and Set Theory",
              start: Date(dateString: "2018-01-15 8:15"),
              end: Date(dateString: "2018-01-15 10:00"),
              room: 103,
              lecturer: "dr Ann Appleseed",
              type: .lecture,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Linear Algebra",
              start: Date(dateString: "2018-01-15 10:15"),
              end: Date(dateString: "2018-01-15 12:00"),
              room: 107,
              lecturer: "dr Tomasz Traczyk",
              type: .lecture,
              webpage: "www.mini.pw.edu.pl/~tomtracz/alg/info_mini.html"),
        Event(name: "Calculus 1",
              start: Date(dateString: "2018-01-15 14:15"),
              end: Date(dateString: "2018-01-15 14:00"),
              room: 213,
              lecturer: "dr Adam Kowalsky",
              type: .tutorial,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Electronic Principles",
              start: Date(dateString: "2018-01-15 14:15"),
              end: Date(dateString: "2018-01-15 16:00"),
              room: 107,
              lecturer: "prof Lucas Zimmerman",
              type: .lecture,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Physics 1",
              start: Date(dateString: "2018-01-15 16:15"),
              end: Date(dateString: "2018-01-15 17:00"),
              room: 212,
              lecturer: "dr Andrzej Sausage",
              type: .lab,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Programming 1",
              start: Date(dateString: "2018-01-16 12:15"),
              end: Date(dateString: "2018-01-16 14:00"),
              room: 211,
              lecturer: "mgr Steve Wozniak",
              type: .tutorial,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Electronic Principles",
              start: Date(dateString: "2018-01-16 14:15"),
              end: Date(dateString: "2018-01-16 16:00"),
              room: 212,
              lecturer: "prof Lucas Zimmerman",
              type: .tutorial,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Discrete Mathematics",
              start: Date(dateString: "2018-01-16 16:15"),
              end: Date(dateString: "2018-01-16 18:00"),
              room: 212,
              lecturer: "dr Mary Nowak",
              type: .lecture,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Logic and Set Theory",
              start: Date(dateString: "2018-01-17 10:15"),
              end: Date(dateString: "2018-01-17 12:00"),
              room: 214,
              lecturer: "dr Ann Appleseed",
              type: .tutorial,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Physics 1",
              start: Date(dateString: "2018-01-17 12:15"),
              end: Date(dateString: "2018-01-17 14:00"),
              room: 107,
              lecturer: "prof Rick Sanchez",
              type: .lecture,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Programming 1",
              start: Date(dateString: "2018-01-17 14:15"),
              end: Date(dateString: "2018-01-17 16:00"),
              room: 103,
              lecturer: "mgr Steve Wozniak",
              type: .lecture,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Calculus 1",
              start: Date(dateString: "2018-01-19 10:15"),
              end: Date(dateString: "2018-01-19 12:00"),
              room: 107,
              lecturer: "mgr Adam Kowalsky",
              type: .lecture,
              webpage: "www.example.com/lecturer/resources"),
        Event(name: "Linear Algebra",
              start: Date(dateString: "2018-01-19 14:15"),
              end: Date(dateString: "2018-01-19 16:00"),
              room: 107,
              lecturer: "dr Tomasz Traczyk",
              type: .lecture,
              webpage: "www.mini.pw.edu.pl/~tomtracz/alg/info_mini.html"),
        Event(name: "Programming 1",
              start: Date(dateString: "2018-01-19 16:15"),
              end: Date(dateString: "2018-01-19 18:00"),
              room: 212,
              lecturer: "dr Peter Nowak",
              type: .lab,
              webpage: "www.example.com/lecturer/resources"),

    ]
}
